# Generated by Django 2.2.16 on 2022-01-02 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('total', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Expired', 'Expired'), ('Paid', 'Paid'), ('Declined', 'Declined')], max_length=20)),
                ('date_issued', payments.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('date_of_deadline', models.DateTimeField(blank=True, null=True)),
                ('date_of_payment', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
