# Generated by Django 2.2.16 on 2022-01-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_loans', '0002_auto_20220101_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('refused', 'Refused'), ('finished', 'Finished')], default='Pending', max_length=24),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('refused', 'Refused'), ('finished', 'Finished')], default='Pending', max_length=24),
        ),
    ]
